// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzEIvnX8cAbWtiCwTt-d4Y2GdOkP7jtns',
    appId: '1:1049370077159:web:3871e504bc0fc8001cbf42',
    messagingSenderId: '1049370077159',
    projectId: 'myswiper-app',
    authDomain: 'myswiper-app.firebaseapp.com',
    storageBucket: 'myswiper-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLCg70SzpdaDD32OFfcM7LL_8uuLOFyBs',
    appId: '1:1049370077159:android:2c23672e829f3c0c1cbf42',
    messagingSenderId: '1049370077159',
    projectId: 'myswiper-app',
    storageBucket: 'myswiper-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDosEL6whFiXwszpNiK2K3XgslywRYzRnE',
    appId: '1:1049370077159:ios:8062eef98d2335351cbf42',
    messagingSenderId: '1049370077159',
    projectId: 'myswiper-app',
    storageBucket: 'myswiper-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDosEL6whFiXwszpNiK2K3XgslywRYzRnE',
    appId: '1:1049370077159:ios:8062eef98d2335351cbf42',
    messagingSenderId: '1049370077159',
    projectId: 'myswiper-app',
    storageBucket: 'myswiper-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzEIvnX8cAbWtiCwTt-d4Y2GdOkP7jtns',
    appId: '1:1049370077159:web:e3b3f6517049fab71cbf42',
    messagingSenderId: '1049370077159',
    projectId: 'myswiper-app',
    authDomain: 'myswiper-app.firebaseapp.com',
    storageBucket: 'myswiper-app.firebasestorage.app',
  );
}
